/**
 * Smart Wallet Tracker — NVR Capital
 *
 * Tracks a seed list of known early/professional Base ecosystem wallets.
 * For any token candidate, checks if these wallets have recently bought it.
 * 2+ smart wallets accumulating the same token = strong pre-movement signal.
 *
 * Uses Base RPC — no API key required. Queries eth_getLogs for ERC-20 Transfer events.
 */

import axios from 'axios';

// ============================================================================
// SEED WALLET LIST
// ============================================================================

/**
 * Bootstrapped from on-chain analysis: wallets active across 4-5 of 6 known
 * Base movers (BRETT, DEGEN, VIRTUAL, AERO, TOSHI, MOCHI) in the last 48h.
 * Generated by: npm run bootstrap-wallets (2026-04-14)
 *
 * Note: some entries may be DEX aggregators (LI.FI, 1inch) which appear on
 * all tokens by nature — even aggregator traffic on a new discovery token is
 * a signal that real demand exists. Refine with registerSmartWallet() over time.
 */
const SMART_WALLETS: Record<string, string> = {
  'base-smart-01': '0x00c600b30fb0400701010f4b080409018b9006e0', // 5/6 movers: AERO+BRETT+MOCHI+TOSHI+VIRTUAL
  'base-smart-02': '0x1231deb6f5749ef6ce6943a275a1d3e7486f4eae', // 5/6 movers (likely LI.FI bridge)
  'base-smart-03': '0x139b578ee197afde49f41fc05657562c4264c84c', // 5/6 movers: AERO+BRETT+MOCHI+TOSHI+VIRTUAL
  'base-smart-04': '0x2aa7d880b7ad5964c02b919074fb27a71a7ddd07', // 5/6 movers: AERO+BRETT+MOCHI+TOSHI+VIRTUAL
  'base-smart-05': '0x4409921ae43a39a11d90f7b7f96cfd0b8093d9fc', // 5/6 movers: AERO+BRETT+MOCHI+TOSHI+VIRTUAL
  'base-smart-06': '0x5aafc1f252d544f744d17a4e734afd6efc47ede4', // 5/6 movers: AERO+BRETT+MOCHI+TOSHI+VIRTUAL
  'base-smart-07': '0x63242a4ea82847b20e506b63b0e2e2eff0cc6cb0', // 5/6 movers: AERO+BRETT+MOCHI+TOSHI+VIRTUAL
  'base-smart-08': '0x7747f8d2a76bd6345cc29622a946a929647f2359', // 5/6 movers: AERO+BRETT+MOCHI+TOSHI+VIRTUAL
  'base-smart-09': '0xc10ee9031f2a0b84766a86b55a8d90f357910fb4', // 5/6 movers: AERO+BRETT+MOCHI+TOSHI+VIRTUAL
  'base-smart-10': '0x000010036c0190e009a000d0fc3541100a07380a', // 4/6 movers: AERO+BRETT+MOCHI+TOSHI
  'base-smart-11': '0x0a2854fbbd9b3ef66f17d47284e7f899b9509330', // 4/6 movers: AERO+BRETT+MOCHI+TOSHI
  'base-smart-12': '0x0b804138fdbd4263a94e81521aa65b384819e309', // 4/6 movers: AERO+BRETT+MOCHI+TOSHI
  'base-smart-13': '0x111111125421ca6dc452d289314280a0f8842a65', // 4/6 movers (1inch router)
  'base-smart-14': '0x19dd96094f3204fa76f65c7b109624cfb62fb17b', // 4/6 movers: AERO+BRETT+TOSHI+VIRTUAL
  'base-smart-15': '0x278d858f05b94576c1e6f73285886876ff6ef8d2', // 4/6 movers: AERO+BRETT+TOSHI+VIRTUAL
  'base-smart-16': '0x411d2c093e4c2e69bf0d8e94be1bf13dadd879c6', // 4/6 movers: AERO+BRETT+TOSHI+VIRTUAL
  'base-smart-17': '0x43f9a7aec2a683c4cd6016f92ff76d5f3e7b44d3', // 4/6 movers: AERO+BRETT+TOSHI+VIRTUAL
  'base-smart-18': '0x498581ff718922c3f8e6a244956af099b2652b2b', // 4/6 movers: AERO+BRETT+MOCHI+TOSHI
  'base-smart-19': '0x4c3ccc98c01103be72bcfd29e1d2454c98d1a6e3', // 4/6 movers: AERO+BRETT+MOCHI+TOSHI
  'base-smart-20': '0x4e48d4885871b4dd2ea91a2aed9390b8908fe525', // 4/6 movers: AERO+BRETT+MOCHI+TOSHI
};

// ============================================================================
// TYPES
// ============================================================================

export interface SmartWalletActivity {
  walletId: string;             // key from SMART_WALLETS map
  walletAddress: string;
  tokenAddress: string;
  buyCount: number;             // number of buy transactions in window
  estimatedVolumeUSD: number;   // rough USD volume (token amount * current price)
  firstBuyTimestamp: number;    // earliest buy in the window (ms)
  lastBuyTimestamp: number;     // most recent buy (ms)
}

export interface WalletExitActivity {
  walletId: string;
  walletAddress: string;
  tokenAddress: string;
  sellCount: number;            // number of outgoing transfers in window
  firstSellTimestamp: number;
  lastSellTimestamp: number;
}

export interface SmartWalletSignal {
  tokenAddress: string;
  activeWallets: SmartWalletActivity[];
  walletCount: number;          // how many distinct smart wallets are in this token
  signalStrength: 'STRONG' | 'MODERATE' | 'WEAK' | 'NONE';
  // STRONG = 3+ wallets, MODERATE = 2 wallets, WEAK = 1 wallet, NONE = 0
  totalVolumeUSD: number;
  earliestActivityMs: number;   // when did the first smart wallet enter
  exitingWallets: WalletExitActivity[];   // wallets sending tokens OUT (selling signal)
  exitSignalStrength: 'STRONG' | 'MODERATE' | 'WEAK' | 'NONE';
  // STRONG = 3+ wallets exiting, MODERATE = 2, WEAK = 1, NONE = 0
}

// ============================================================================
// CONSTANTS
// ============================================================================

const BASE_RPC_URL = 'https://mainnet.base.org';
const BATCH_SIZE = 3;           // concurrent wallet checks
const BATCH_DELAY_MS = 250;     // 250 ms between batches

// Minimum number of signals a wallet must have before its weight is used
const MIN_SIGNALS_FOR_WEIGHT = 5;

// ============================================================================
// WALLET WEIGHTS — updated by outcome tracker based on historical hit rates
// ============================================================================

/**
 * Stores per-wallet hit rates (0-1) as learned from historical outcomes.
 * Populated by updateWalletWeight() called from the outcome tracker.
 * Default weight 0.5 (neutral) used for wallets without sufficient history.
 */
const WALLET_WEIGHTS: Map<string, number> = new Map();

// Track how many signals each wallet has contributed (to gate on MIN_SIGNALS_FOR_WEIGHT)
const WALLET_SIGNAL_COUNTS: Map<string, number> = new Map();

/**
 * Update a wallet's weight based on its observed 4h hit rate.
 * Called periodically by the outcome tracker after computing WalletHitRates.
 *
 * @param walletId    Key from SMART_WALLETS (e.g. 'base-smart-01')
 * @param hitRate4h   Fraction of signals where token went up >10% in 4h (0-1)
 * @param totalSignals Total number of times this wallet appeared in a surfaced token
 */
export function updateWalletWeight(walletId: string, hitRate4h: number, totalSignals: number): void {
  WALLET_WEIGHTS.set(walletId, hitRate4h);
  WALLET_SIGNAL_COUNTS.set(walletId, totalSignals);
}

/**
 * Get the learned weight for a wallet.
 * Returns 0.5 (neutral) when the wallet has insufficient history.
 */
export function getWalletWeight(walletId: string): number {
  const signals = WALLET_SIGNAL_COUNTS.get(walletId) ?? 0;
  if (signals < MIN_SIGNALS_FOR_WEIGHT) return 0.5; // not enough data yet
  return WALLET_WEIGHTS.get(walletId) ?? 0.5;
}

// ============================================================================
// HELPERS
// ============================================================================

/**
 * Compute the average hit-rate-weighted signal strength for a set of active wallets.
 * Returns the signal strength, potentially downgraded if wallets have poor track records.
 *
 * Downgrade rules (only applied when wallets have >= MIN_SIGNALS_FOR_WEIGHT history):
 *   - STRONG from wallets with avg hitRate4h < 0.3  → MODERATE
 *   - STRONG from wallets with avg hitRate4h > 0.6  → stays STRONG
 *   - MODERATE and WEAK are not upgraded/downgraded (insufficient data impact)
 */
function mapSignalStrength(
  walletCount: number,
  activeWalletIds?: string[],
): SmartWalletSignal['signalStrength'] {
  const rawStrength: SmartWalletSignal['signalStrength'] =
    walletCount >= 3 ? 'STRONG' :
    walletCount === 2 ? 'MODERATE' :
    walletCount === 1 ? 'WEAK' :
    'NONE';

  // Only apply weight-based adjustment to STRONG signals
  if (rawStrength !== 'STRONG' || !activeWalletIds || activeWalletIds.length === 0) {
    return rawStrength;
  }

  // Check if any wallet has enough history to influence the signal
  const qualifiedWeights = activeWalletIds
    .filter(id => (WALLET_SIGNAL_COUNTS.get(id) ?? 0) >= MIN_SIGNALS_FOR_WEIGHT)
    .map(id => WALLET_WEIGHTS.get(id) ?? 0.5);

  // If no wallet has sufficient history, return raw strength unchanged
  if (qualifiedWeights.length === 0) return rawStrength;

  const avgWeight = qualifiedWeights.reduce((s, w) => s + w, 0) / qualifiedWeights.length;

  if (avgWeight < 0.3) return 'MODERATE'; // known poor predictors — downgrade
  // avgWeight > 0.6 stays STRONG (no upgrade needed, already at max)
  return rawStrength;
}

/**
 * Check a single wallet for token buy activity within the lookback window.
 * Returns null on any failure — callers filter nulls.
 * Uses Base RPC — no API key required.
 */
async function checkSingleWallet(
  walletId: string,
  walletAddress: string,
  tokenAddress: string,
  tokenPriceUSD: number,
  lookbackHours: number,
): Promise<SmartWalletActivity | null> {
  try {
    // Get current block
    const blockNumRes = await axios.post(BASE_RPC_URL, {
      jsonrpc: '2.0', id: 1, method: 'eth_blockNumber', params: []
    }, { timeout: 8000 });
    const currentBlock = parseInt(blockNumRes.data.result, 16);

    const blocksBack = Math.floor(lookbackHours * 1800); // ~2s/block → 1800 blocks/hour
    const fromBlock = currentBlock - blocksBack;

    // Query Transfer events TO this wallet for this token
    // topic[1] = from (null = any), topic[2] = to (wallet address padded)
    const paddedWallet = '0x' + walletAddress.toLowerCase().replace('0x', '').padStart(64, '0');

    const logsRes = await axios.post(BASE_RPC_URL, {
      jsonrpc: '2.0',
      id: 1,
      method: 'eth_getLogs',
      params: [{
        fromBlock: `0x${fromBlock.toString(16)}`,
        toBlock: `0x${currentBlock.toString(16)}`,
        address: tokenAddress,
        topics: [
          '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
          null,        // from: any
          paddedWallet // to: this wallet
        ],
      }],
    }, { timeout: 12000 });

    const logs = logsRes.data?.result || [];
    if (logs.length === 0) return null;

    // Parse timestamps from block numbers
    const timestamps = logs.map((log: any) => {
      const blockNum = parseInt(log.blockNumber, 16);
      // Approximate timestamp: currentBlock is now, each block ~2s
      return Date.now() - (currentBlock - blockNum) * 2000;
    });

    // Estimate volume: each log's data field contains the token amount
    let totalTokens = BigInt(0);
    for (const log of logs) {
      try { totalTokens += BigInt(log.data); } catch { /* skip */ }
    }
    // Rough USD estimate (tokenPriceUSD is per whole token, decimals unknown → use 1e18)
    const estimatedVolumeUSD = Number(totalTokens) / 1e18 * tokenPriceUSD;

    return {
      walletId,
      walletAddress,
      tokenAddress: tokenAddress.toLowerCase(),
      buyCount: logs.length,
      estimatedVolumeUSD,
      firstBuyTimestamp: Math.min(...timestamps),
      lastBuyTimestamp: Math.max(...timestamps),
    };
  } catch {
    // Swallow per-wallet errors — don't spam logs
    return null;
  }
}

/**
 * Check a single wallet for token SELL (exit) activity within the lookback window.
 * Mirrors checkSingleWallet() but flips the topic filter:
 *   topics[1] = paddedWallet (from: this wallet = outgoing)
 *   topics[2] = null         (to: any)
 * Returns null on any failure — callers filter nulls.
 */
async function checkSingleWalletExit(
  walletId: string,
  walletAddress: string,
  tokenAddress: string,
  lookbackHours: number,
): Promise<WalletExitActivity | null> {
  try {
    // Get current block
    const blockNumRes = await axios.post(BASE_RPC_URL, {
      jsonrpc: '2.0', id: 1, method: 'eth_blockNumber', params: []
    }, { timeout: 8000 });
    const currentBlock = parseInt(blockNumRes.data.result, 16);

    const blocksBack = Math.floor(lookbackHours * 1800); // ~2s/block → 1800 blocks/hour
    const fromBlock = currentBlock - blocksBack;

    // Query Transfer events FROM this wallet for this token
    // topic[1] = from (wallet address padded), topic[2] = to (null = any)
    const paddedWallet = '0x' + walletAddress.toLowerCase().replace('0x', '').padStart(64, '0');

    const logsRes = await axios.post(BASE_RPC_URL, {
      jsonrpc: '2.0',
      id: 1,
      method: 'eth_getLogs',
      params: [{
        fromBlock: `0x${fromBlock.toString(16)}`,
        toBlock: `0x${currentBlock.toString(16)}`,
        address: tokenAddress,
        topics: [
          '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
          paddedWallet, // from: this wallet
          null,         // to: any
        ],
      }],
    }, { timeout: 12000 });

    const logs = logsRes.data?.result || [];
    if (logs.length === 0) return null;

    // Parse timestamps from block numbers
    const timestamps = logs.map((log: any) => {
      const blockNum = parseInt(log.blockNumber, 16);
      return Date.now() - (currentBlock - blockNum) * 2000;
    });

    return {
      walletId,
      walletAddress,
      tokenAddress: tokenAddress.toLowerCase(),
      sellCount: logs.length,
      firstSellTimestamp: Math.min(...timestamps),
      lastSellTimestamp: Math.max(...timestamps),
    };
  } catch {
    // Swallow per-wallet errors — fail open
    return null;
  }
}

// ============================================================================
// PRIMARY EXPORT
// ============================================================================

/**
 * Check all tracked smart wallets for recent buy activity on a token.
 *
 * Returns a SmartWalletSignal describing how many professional wallets have
 * entered the position within the lookback window. Use this as a confirmation
 * layer before entering a trade — if 2+ smart wallets are already in, the
 * token has stealth accumulation occurring ahead of any public catalyst.
 *
 * @param tokenAddress   ERC-20 token address on Base
 * @param tokenPriceUSD  Current token price used to estimate USD volume
 * @param lookbackHours  How far back to scan (default: 24h)
 */
export async function checkSmartWalletActivity(
  tokenAddress: string,
  tokenPriceUSD: number,
  lookbackHours: number = 24,
): Promise<SmartWalletSignal> {
  const NONE_SIGNAL: SmartWalletSignal = {
    tokenAddress: tokenAddress.toLowerCase(),
    activeWallets: [],
    walletCount: 0,
    signalStrength: 'NONE',
    totalVolumeUSD: 0,
    earliestActivityMs: 0,
    exitingWallets: [],
    exitSignalStrength: 'NONE',
  };

  const walletEntries = Object.entries(SMART_WALLETS);
  const results: SmartWalletActivity[] = [];
  const exitResults: WalletExitActivity[] = [];

  // Batch wallet checks in groups to avoid overwhelming the public RPC.
  // Buy and exit checks run concurrently per wallet — total time stays ~= current,
  // not 2x, because both directions are fetched in parallel inside each batch.
  for (let i = 0; i < walletEntries.length; i += BATCH_SIZE) {
    const batch = walletEntries.slice(i, i + BATCH_SIZE);

    const batchPairs = await Promise.all(
      batch.map(([id, addr]) =>
        Promise.all([
          checkSingleWallet(id, addr, tokenAddress, tokenPriceUSD, lookbackHours),
          checkSingleWalletExit(id, addr, tokenAddress, lookbackHours),
        ]),
      ),
    );

    for (const [buyResult, exitResult] of batchPairs) {
      if (buyResult !== null) results.push(buyResult);
      if (exitResult !== null) exitResults.push(exitResult);
    }

    // Delay between batches (skip after final batch)
    if (i + BATCH_SIZE < walletEntries.length) {
      await new Promise<void>((resolve) => setTimeout(resolve, BATCH_DELAY_MS));
    }
  }

  // If every single wallet check failed, return NONE
  if (results.length === 0 && exitResults.length === 0 && walletEntries.length > 0) {
    return NONE_SIGNAL;
  }

  const totalVolumeUSD = results.reduce((sum, r) => sum + r.estimatedVolumeUSD, 0);
  const earliestActivityMs =
    results.length > 0 ? Math.min(...results.map((r) => r.firstBuyTimestamp)) : 0;

  const activeWalletIds = results.map((r) => r.walletId);

  return {
    tokenAddress: tokenAddress.toLowerCase(),
    activeWallets: results,
    walletCount: results.length,
    signalStrength: mapSignalStrength(results.length, activeWalletIds),
    totalVolumeUSD,
    earliestActivityMs,
    exitingWallets: exitResults,
    exitSignalStrength: mapSignalStrength(exitResults.length),
  };
}

// ============================================================================
// RUNTIME WALLET MANAGEMENT
// ============================================================================

/**
 * Add a newly identified profitable wallet to the tracking list.
 * Addresses are normalised to lowercase for consistent comparison.
 */
export function registerSmartWallet(id: string, address: string): void {
  SMART_WALLETS[id] = address.toLowerCase();
}

/**
 * Return a snapshot of the current smart wallet list.
 * Callers receive a copy — mutations do not affect the internal map.
 */
export function getSmartWallets(): Record<string, string> {
  return { ...SMART_WALLETS };
}
