/**
 * v19.0: Weekly Strategy Performance Report
 *
 * Generates a comprehensive markdown report from the last 7 days of trading data.
 * Runs every Sunday at midnight (checked each cycle). Stores the latest report
 * in memory for the /api/weekly-report endpoint.
 */

export interface WeeklyReportData {
  generatedAt: string;
  periodStart: string;
  periodEnd: string;
  version: string;

  // Performance
  startingValue: number;
  endingValue: number;
  periodPnL: number;
  periodPnLPercent: number;
  maxDrawdown: number;

  // Trading activity
  totalTrades: number;
  buys: number;
  sells: number;
  winRate: number;
  avgWin: number;
  avgLoss: number;
  largestWin: { token: string; amount: number };
  largestLoss: { token: string; amount: number };

  // Strategy breakdown
  tradesByTier: Record<string, number>;
  flowReversalExits: number;
  scoutSeeds: number;
  surgeScaleUps: number;

  // Signal quality
  signalsGenerated: number;
  signalsExecuted: number;
  signalsFiltered: number;
  topFilterReasons: Array<{ reason: string; count: number }>;

  markdown: string;
}

let latestReport: WeeklyReportData | null = null;
let lastReportDate: string | null = null;

interface TradeRecord {
  timestamp: string;
  action: string;
  fromToken?: string;
  toToken?: string;
  amountUSD: number;
  success: boolean;
  reasoning?: string;
  pnlUSD?: number;
}

export function generateWeeklyReport(
  tradeHistory: TradeRecord[],
  currentPortfolioValue: number,
  version: string,
): WeeklyReportData {
  const now = new Date();
  const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
  const periodStart = weekAgo.toISOString().split('T')[0];
  const periodEnd = now.toISOString().split('T')[0];

  // Filter trades to this week
  const weekTrades = tradeHistory.filter(t => new Date(t.timestamp) >= weekAgo && t.success);

  const buys = weekTrades.filter(t => t.action === 'BUY');
  const sells = weekTrades.filter(t => t.action === 'SELL');

  // Calculate wins/losses from sells with P&L data
  const sellsWithPnL = sells.filter(t => t.pnlUSD !== undefined);
  const wins = sellsWithPnL.filter(t => (t.pnlUSD || 0) > 0);
  const losses = sellsWithPnL.filter(t => (t.pnlUSD || 0) <= 0);
  const winRate = sellsWithPnL.length > 0 ? (wins.length / sellsWithPnL.length) * 100 : 0;
  const avgWin = wins.length > 0 ? wins.reduce((s, t) => s + (t.pnlUSD || 0), 0) / wins.length : 0;
  const avgLoss = losses.length > 0 ? losses.reduce((s, t) => s + Math.abs(t.pnlUSD || 0), 0) / losses.length : 0;

  // Largest win/loss
  let largestWin = { token: '-', amount: 0 };
  let largestLoss = { token: '-', amount: 0 };
  for (const t of sellsWithPnL) {
    if ((t.pnlUSD || 0) > largestWin.amount) {
      largestWin = { token: t.fromToken || '?', amount: t.pnlUSD || 0 };
    }
    if ((t.pnlUSD || 0) < -largestLoss.amount) {
      largestLoss = { token: t.fromToken || '?', amount: Math.abs(t.pnlUSD || 0) };
    }
  }

  // Trade tier breakdown
  const tradesByTier: Record<string, number> = {};
  for (const t of weekTrades) {
    const tier = t.reasoning?.match(/^([A-Z_]+):/)?.[1] || 'AI';
    tradesByTier[tier] = (tradesByTier[tier] || 0) + 1;
  }

  const flowReversalExits = tradesByTier['FLOW_REVERSAL'] || 0;
  const scoutSeeds = tradesByTier['SCOUT'] || 0;
  const surgeScaleUps = weekTrades.filter(t => t.reasoning?.includes('confirmed across')).length;

  // Estimate period P&L (rough — uses current value vs 7-day-ago value if available)
  const periodPnL = 0; // Would need historical snapshots for accuracy
  const periodPnLPercent = 0;

  // Build markdown
  const md = `# NVR Weekly Performance Report
**Period:** ${periodStart} to ${periodEnd}
**Version:** ${version}
**Generated:** ${now.toISOString()}

---

## Portfolio Performance
| Metric | Value |
|--------|-------|
| Current Value | $${currentPortfolioValue.toFixed(2)} |
| Total Trades (Week) | ${weekTrades.length} |
| Buys | ${buys.length} |
| Sells | ${sells.length} |
| Win Rate | ${winRate.toFixed(1)}% |
| Avg Win | $${avgWin.toFixed(2)} |
| Avg Loss | $${avgLoss.toFixed(2)} |
| Largest Win | ${largestWin.token} +$${largestWin.amount.toFixed(2)} |
| Largest Loss | ${largestLoss.token} -$${largestLoss.amount.toFixed(2)} |

## Strategy Breakdown
${Object.entries(tradesByTier)
  .sort((a, b) => b[1] - a[1])
  .map(([tier, count]) => `- **${tier}**: ${count} trades`)
  .join('\n')}

## v19.0 Flow Physics
- Flow-reversal exits: ${flowReversalExits}
- Scout positions seeded: ${scoutSeeds}
- Surge scale-ups: ${surgeScaleUps}

---
*Generated by NVR v${version} — Always watching. Always adapting. Never resting.*
`;

  const report: WeeklyReportData = {
    generatedAt: now.toISOString(),
    periodStart,
    periodEnd,
    version,
    startingValue: 0,
    endingValue: currentPortfolioValue,
    periodPnL,
    periodPnLPercent,
    maxDrawdown: 0,
    totalTrades: weekTrades.length,
    buys: buys.length,
    sells: sells.length,
    winRate,
    avgWin,
    avgLoss,
    largestWin,
    largestLoss,
    tradesByTier,
    flowReversalExits,
    scoutSeeds,
    surgeScaleUps,
    signalsGenerated: 0,
    signalsExecuted: 0,
    signalsFiltered: 0,
    topFilterReasons: [],
    markdown: md,
  };

  latestReport = report;
  lastReportDate = periodEnd;
  return report;
}

export function shouldGenerateReport(): boolean {
  const now = new Date();
  // Generate on Sunday (day 0)
  if (now.getUTCDay() !== 0) return false;
  // Only once per day
  const today = now.toISOString().split('T')[0];
  if (lastReportDate === today) return false;
  // Only during the first hour (UTC midnight window)
  if (now.getUTCHours() > 1) return false;
  return true;
}

export function getLatestReport(): WeeklyReportData | null {
  return latestReport;
}
